### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by 8bitgentleman** [mconway/firefly-app#1]
Just downloaded this app after seeing it mentioned on the firefly-iii subreddit. I am trying to log in but have run into some issues. Following the instructions [here](https://github.com/mconway/firefly-app/wiki) I set up the Oauth Client in Firefly-iii, I put in my firefly url, my client ID, and client secret. Upon hitting save I just get a blank white screen. No prompt to enter credentials or anything. Is this broken or am I missing something? I'm on a Pixel 2 running Oreo.
Thanks!

**Comment by mconway** [comment]
Typically if there is a blank box that appears after hitting save, that indicates either the URL you entered for Firefly is incorrect or inaccessible. I'll try to make it more apparent in my next release. 

Please double check your URL. If you still have issues, please post a screenshot.

**Comment by 8bitgentleman** [comment]
The URL was the issue. I've just got firefly on an open port right now so I had to change the url from IP:PORT to http://IP:PORT/

Thanks
