### ISSUE TITLE
Downloaded latest update, app is stuck loading

### ISSUE THREAD

**Issue by tdoerrich** [mconway/firefly-app#16]
I got the latest update today and now all the app does is loading. It has the black transparent screen on top and loads, loads and loads. But I can't use the app at all anymore.

On a OnePlus 3

**Comment by tdoerrich** [comment]
Photo: https://cloud.postnow.eu/index.php/s/tRbkdqKKiEHa5ks

**Comment by mconway** [comment]
You know, once when I was testing I had that happen. Closing the app (kill it) and reopening it worked, and it never came back. 

I haven't had that issue on my phone. If you still have issues I'll try to push out a fix today. Sorry for the inconveniences!

**Comment by tdoerrich** [comment]
Sure. And sadly didn't work for me. Even with a full phone restart. :(

**Comment by mconway** [comment]
Ok, I'll take a look this afternoon. Sorry!

**Comment by mconway** [comment]
V 0.7.692 was released to resolve this issue.

**Comment by tdoerrich** [comment]
Is that already released in Google Play Store as well?

**Comment by mconway** [comment]
I apparently missed hitting "publish" last night on the Play Store. It should be available momentarily.
