### ISSUE TITLE
Weird FAB everywhere

### ISSUE THREAD

**Issue by emansih** [mconway/firefly-app#19]
![firefly-app](https://user-images.githubusercontent.com/5896415/46580744-66c8b900-ca5d-11e8-94da-9d9066abbde1.jpg)

This FAB is quite out of place, showing up everywhere. What i propose is to show the FAB only in the home page and transaction page since it only does one thing, which is to add transactions. Thoughts?

**Comment by mconway** [comment]
I've been working on making this better, I haven't quite limited it to just the home screen yet - though that's what I'm leaning toward. I've also moved it to the bottom right. Here's a screenshot.
![image](https://user-images.githubusercontent.com/411506/46642621-f8532c00-cb2c-11e8-98e4-c1ff323f0de1.png)
