### ISSUE TITLE
Undefined value in Piggy Bank

### ISSUE THREAD

**Issue by emansih** [mconway/firefly-app#20]
The chart displayed in the piggy bank chart has `undefined` labels instead of `Saved` and `To save` labels
![piggybank](https://user-images.githubusercontent.com/5896415/46606591-52092580-cb30-11e8-9083-cfcce965d1bf.jpg)

**Comment by mconway** [comment]
Thanks, I was aware of that - basically I havne't put in enough time to disable labels completely on the charts quite yet. I'll try to have it fixed for the next release.
