### ISSUE TITLE
An error occurred getting token: OK

### ISSUE THREAD

**Issue by evolsano** [mconway/firefly-app#22]
I have a firefly docker container running with traefik reverse proxy and LetsEncrypt https enabled. Everything works well with browser. But I have problem to use the app.

I configured it as per the wiki, generated OAuth clients, I can get until the screen to authorize app, but it back to the setting page and show "An error occurred getting token: OK"

If I use postman, it authorized the app successfully, and I can see the authorized app in firefly profile page.
Please let me know if you require any information for the troubleshooting.

![image](https://user-images.githubusercontent.com/8122147/48531164-1eab7a80-e8d6-11e8-9f84-977941cc495f.png)

![image](https://user-images.githubusercontent.com/8122147/48531196-4d295580-e8d6-11e8-876b-8bf6c4948559.png)

**Comment by mconway** [comment]
Hmm, this one will probably require some troubleshooting.

1. What version of Firefly are you running?
2. Are you actually seeing the "authorize app" screen? This would be the one that appears once you enter your username and password. Is the error occuring after you hit the button to authorize the app?
3. would you be willing to (privately) provide me a test account to your setup so I can take a look at the network traffic if we get to that point?

**Comment by evolsano** [comment]
1. What version of Firefly are you running? _**Version 4.7.8**_
2. Are you actually seeing the "authorize app" screen? This would be the one that appears once you enter your username and password. Is the error occuring after you hit the button to authorize the app? _**Yes. I saw the authoriz app green button, and it go to the login page after click it. However, the error "An error occurred getting token: OK" prompted after I enter my username and password from the login screen.**_
3. would you be willing to (privately) provide me a test account to your setup so I can take a look at the network traffic if we get to that point? _**May I know what kind of account you required? It is running in docker and don't have public access.**_

**Comment by mconway** [comment]
I'm thinking it something in the routing in web requests. I'd just need a dummy account for your firefly instance, as well as a URL to access it.

**Comment by evolsano** [comment]
Please let me know how to send you the account and URL access.

**Comment by mconway** [comment]
you can send the information to support at zerobytesolutions dot com.

thanks!

**Comment by mconway** [comment]
I never heard back from you. I used thet est account you sent me, but everything worked on my end. Were you able to get it to work?

**Comment by evolsano** [comment]
Somehow it is working now and I didn't do any change.
