### ISSUE TITLE
2FA Support?

### ISSUE THREAD

**Issue by 4oo4** [mconway/firefly-app#23]
I was curious if the app supports a Firefly account that has 2FA enabled, and if not, if there are plans to add this? Or perhaps if this isn't supported currently by the Firefly API itself?

I'm having difficulty getting my app to connect with my Firefly instance, even though I've created an OAuth client correctly, whenever I go to log into the app, after giving it the client ID/secret and I go to the login screen, after the username/password I see a Not Authorized error from the API. I can then hit the back button to enter my 2FA token, but it then takes me to what looks like using Electron to view the browser page, when based on [this](https://github.com/mconway/firefly-app/issues/22) I think it's supposed to take me to the Authorize App screen, at which point the app itself will start to pull in in data?

Just upgraded to Firefly v. 4.7.9, but the issue also occurred with earlier versions (so, no change with the big API rewrite).

Cheers

**Error message**
` {"error": "invalid_client", "message" "Client Authentication Failed"}`

**Screenshot**
![screenshot_20181223-194609_firefly-app](https://user-images.githubusercontent.com/15698835/50389182-daa26580-071e-11e9-9320-236d8ff5b3e8.png)

**Comment by mconway** [comment]
I haven't had any issues using 2FA, it's been enabled on my instance for quite a while now. Typically the error you see occurs when the token and client id do not match.

That said, I've been having an issue that seems to have started randomly where I can't authorize the app from my phone that i'm investigating. I doubt they are related though.

What should happen is after you hit the green authorize button (assuming you got that far), then the window will close and you will see a toast notification that connection was established. If you aren't getting past the login to the green authorize button, then i'd say your Client ID and Token are incorrect.

**Comment by 4oo4** [comment]
Gotcha, I'll keep testing and see if I can get it working, since it's working for you. Thanks!

**EDIT:** Just created a new client and that worked perfectly, I think I created the first Oauth client forever ago, so something weird must have happened with that, for some reason it still shows as valid according to the server.

¯\_(ツ)_/¯

Thanks again!
