### ISSUE TITLE
How to connect to a sandstorm server

### ISSUE THREAD

**Issue by professor-cowboy** [mconway/firefly-app#24]
Hi, i'm using firefly on sandstorm but i don't know how to connect your app to my sandstorm server

**Comment by professor-cowboy** [comment]
a relevant discussion on the firefly-iii github: https://github.com/firefly-iii/firefly-iii/issues/1502

**Comment by JC5** [comment]
Firefly III can't be exposed through Sandstorm yet, sorry about that. It requires a custom implementation.
