### ISSUE TITLE
Unable to select accounts when adding transactions

### ISSUE THREAD

**Issue by mwpdxdev** [mconway/firefly-app#25]
## Issue
- Cannot successfully select Source Account or Expense Account when adding a new withdrawal
- Cannot successfully select Source Account or Destination Account when adding a new transfer
- Cannot successfully select Destination Account or Revenue Account when adding a new withdrawal

I have setup expense, revenue and liability accounts on my install of Firefly (local server), each are set to active on the server.  I have input several transactions via the browser, but none through the phone app yet.  I am logged into the server via PAT successfully via the android app.  I can see everything with the exception of the active accounts.

### Environment

Phone: Pixel 3a XL
Android Build: PQ3B: 190705.003
Firefly App Version: 0.9.0.727

Firefly Server Version: 4.7.17
API Version: 0.9.2
Apache 2.4.9

### Expected Behavior
- Be on Overview screen
- Add a new transaction
- Fill in all fields
- Select desired accounts
- Save

### Actual Behavior / Steps To Reproduce
- Be on Overview screen
- Add a new transaction
- Fill in all fields
- All/Any desired accounts are not available (see images)
- Can save without desired accounts (nothing shows up on Firefly server)

### Screenshots
https://imgur.com/a/AX4pVaV

**Comment by dIELERx** [comment]
I can confirm this bug. I am not able to select an account. Same **App version** (0.9.0.727), same **Firefly Version** (4.7.17).

**Webserver**: Nginx Reverse Proxy
**Phone**: Xiaomi Redmi Note 5 (Whyred)

If you need anything, just let me know and I'll update my post.

**Comment by mconway** [comment]
Thanks for confirming, and sorry for my delayed response. I'm currently on vacation, but ill try to take a look as soon as I can. I think I have a pretty good idea of what's happening.

**Comment by mconway** [comment]
I've got this issue fixed and I'm pushing it out the the beta channel on the store. It should propagate in the next couple hours. Sorry for the delay.
