### ISSUE TITLE
OAuth fails - An Errour occured getting Token: Unknown Error

### ISSUE THREAD

**Issue by dIELERx** [mconway/firefly-app#26]
### Environment
**Phone**: Xiaomi Redmi Note 5
**Android Build**: PQ3B: 190801.002
**Android Version:** 9
**Firefly App Version**: 0.9.0.738
**Firefly Server Version**: 4.8.0.3

I am running Firefly with Docker behind a Nginx Reverse Proxy with SSL Support.

--------------------------------------

## Expected Behavior
App gets authorized and I am able to use the app and browse my accounts, add transactions ...

## Current Behavior
As soon as I fill in the OAUTH2 fields with URL, ID and Secret and click "SAVE", I am able to enter my login credentials at the login. 
Afterwards I can "Authorize" or "Cancel" the Authorization Request.
![Screenshot_firefly-app_20190901-160129_1](https://user-images.githubusercontent.com/32218246/64077860-b26afd80-ccd4-11e9-86b5-98aaf26bac56.png)

If I authroize it, an error occured "**An Errour occured getting Token: Unknown Error**"
![Screenshot_firefly-app_20190901-160405_1](https://user-images.githubusercontent.com/32218246/64077869-ca428180-ccd4-11e9-914d-50d9aabf3e48.png)

If I take a look at the Web, I can see the Authorized Application in the Settings. Seems like the authorization did work, but the App did not recognize it somehow. If I try to authenticate again, I have to login with my credentials again and when clicking "Sign in" once, nothing happens. If i hit "Sign in" one more time, I see "419 Page Expired" in the middle of the screen.
![Screenshot_firefly-app_20190901-162948_1](https://user-images.githubusercontent.com/32218246/64077959-c9f6b600-ccd5-11e9-9dbb-0a91713e3935.png)

Does not matter if 2FA is enabled or not.

## Steps to Reproduce
1. Create OAUTH Client via Web and enter following Redirect URL "http://localhost/callback"
2. Fill in Server URL, Client ID and Client Secret
3. Login with credentials
4. Click "Authorize"
5. Error occures (see screenshot)

Is there anything more I can provide to you? 
Thanks

**Comment by mconway** [comment]
This started happening for me the other day as well. I'm looking into it and will hopefully have a fix soon.

**Comment by mconway** [comment]
OK, After a ton of banging my head into a wall, here's what it looks like happened:
Newer versions of Android force the use of Chrome for webview now. This has extra security set up that requires the server to provide explicit access to headers and the app. I have Firefly set up on Docker, with an Nginx reverse proxy. This is what I had to use to get it to work (i put this at the top of the server definition)

```
server {
        listen 443;
        server_name <your domain>;
        ssl_certificate <your cert>;
        ssl_certificate_key <your cert>;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'FETCH, GET,PUT,POST,DELETE,PATCH,OPTIONS';
        add_header 'Access-Control-Expose-Headers' 'Request, Origin, X-Requested-With, Content-Type, Accept';
        add_header 'Access-Control-Allow-Headers' 'Request, Origin, X-Requested-With, Content-Type, Accept, Authorization';
        add_header 'Access-Control-Allow-Credentials' 'true';

        location / {
                proxy_pass http://localhost:8082/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto "https";
        }
}
```

**Comment by mconway** [comment]
One last note for you @dIELERx - I'm currently working on rebuilding the way transactions are pulled by the App since 4.8 was a major overhaul to those endpoints. I have no idea what the app is going to do for you in that regard.

**Comment by dIELERx** [comment]
Man, thanks a lot for your help. Those headers resolved it!

I am using slighty different proxy headers.. Heres my config:
```
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'FETCH, GET,PUT,POST,DELETE,PATCH,OPTIONS';
        add_header 'Access-Control-Expose-Headers' 'Request, Origin, X-Requested-With, Content-Type, Accept';
        add_header 'Access-Control-Allow-Headers' 'Request, Origin, X-Requested-With, Content-Type, Accept, Authorization';
        add_header 'Access-Control-Allow-Credentials' 'true';

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass "http://127.0.0.1:9001";
                proxy_set_header Upgrade           $http_upgrade;
                proxy_set_header Connection        "upgrade";
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host  $host;
                proxy_set_header X-Forwarded-Port  $server_port;
                proxy_set_header X-Forwarded-Proto "https";
```
Could we get those Nginx Reverse Proxy config added to your wiki? Just to make sure, other people don't run into this problem.

**Comment by dIELERx** [comment]
> One last note for you @dIELERx - I'm currently working on rebuilding the way transactions are pulled by the App since 4.8 was a major overhaul to those endpoints. I have no idea what the app is going to do for you in that regard.

Alright, if you ned someone to test stuff, just let me know. I am a big fan of Firefly and having an Android App is even better. Therefore, just let me know what I can do and I'll try to support you.
