### ISSUE TITLE
Transaction doesn't send data to instance

### ISSUE THREAD

**Issue by optimistic5** [mconway/firefly-app#27]
1. New Transaction, Withdrawal.
I filled all necessary field and clicked Save.
See "Transaction Created Successfully"
![image](https://user-images.githubusercontent.com/25054050/64120682-89666d80-cda5-11e9-908a-7c54a8a3743f.png)

2. Menu - Transactions
![image](https://user-images.githubusercontent.com/25054050/64120336-9a62af00-cda4-11e9-8ad2-0accc1f5b137.png)
0 transactions pending. 
Pulled down to update and see that last update was long time ago (10:52, but now 17:06).

3. On my FireFly-iii I don't have this transaction.

So transactions doesn't work. 
Same for Deposit.

Firefly version 4.8.0.3 (Docker)
API version 0.10.1

App version 0.9.0.738

Debug from Firefly app:
Debug information generated at 2019-09-02 17:14:00 Europe/Kiev for Firefly III version **4.8.0.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0.3 |
| FF API version | 0.10.1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.8 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-08-26 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, Zend OPcache |

**Comment by mconway** [comment]
Thanks for this report. I'm currently working on updating the app to work with firefly 4.8, hoping to have an update out by the weekend, but it will depend on my time at my day job.

**Comment by dIELERx** [comment]
I can confirm this as well. I do not see any Transaction in the app and succesfully created transactions insidee the app do not appear at firefly.

**Comment by optimistic5** [comment]
@mconway thank you for your answer.
Your app for me is great because of offline transaction, this is a key feature.
I'll be waiting :)

**Comment by mconway** [comment]
I'm still working on this. It's taking me a bit longer (and I've had less time that anticipated) to get it complete. Much of the heavy lifting is done but I'm just running into some random issues that I have to iron out.

**Comment by mconway** [comment]
I've got most of the models rebuilt on the app to handle the new transaction api. I've just pushed a bunch of changes to my private testing build. Still having issues saving offline transactions. I'll be unavailable the next week - but it's giving me a good chance to test out the changes to the app on my device.

**Comment by mconway** [comment]
I've pushed out an update to the app ( 0.10.0.754) that should address issues with transactions in FF 4.8. There are still a few lingering issues with things such as charts, but interested in feedback to ensure everything is now working to save transactions online/offline.
