### ISSUE TITLE
Support for Euro?

### ISSUE THREAD

**Issue by tdoerrich** [mconway/firefly-app#3]
Just wondering if there is any chance you will add support for Euro in the app?

**Comment by mconway** [comment]
Actually, there should be no issues using the app with Euro (or any other) currency. Except for the fact that the overview page shows $, every other page should show the correct currency. I'm currently working on fixing the overview page to solve the following issues:

1. Use the correct currency for accounts
2. Support multi/mixed currency.

I don't use more than one currency, so I have no real use case to test against. I'll try to have this done in the next release.

**Comment by mconway** [comment]
just wanted to show the progress on this - since the only place that currency codes are still hard coded is the account totals overview, here's what it will look like in the next release.
![image](https://user-images.githubusercontent.com/411506/45799846-bf2d4780-bc63-11e8-9b3c-656b8837043f.png)

**Comment by mconway** [comment]
Taking a bit of a guess here, but I'm betting that because you are using a subdirectory (/public), the url the app is calling is actually https://yoururl.com/oauth/authorize.

Do you have access to the logs on the web server? could you watch the error logs and see the full url being called?
